services:
  #FastAPI (Backend)
  api:
    build: 
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./models/weights:/app/models/weights 
    
  # 2.Streamlit(fronted)
  web:
    build:
      context: .
      dockerfile: src/frontend/Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - api  # 
    environment:
      - API_URL=http://api:8000/predict