name: CI/CD - Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push API
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dental-api:latest

      - name: Build and Push UI
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dental-ui:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to AWS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/dental-api:latest
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/dental-ui:latest
            
            docker stop dental-api dental-ui || true
            docker rm dental-api dental-ui || true
            
            docker run -d --name dental-api -p 8000:8000 ${{ secrets.DOCKERHUB_USERNAME }}/dental-api:latest
            docker run -d --name dental-ui -p 8501:8501 -e API_URL=http://${{ secrets.EC2_HOST }}:8000/predict ${{ secrets.DOCKERHUB_USERNAME }}/dental-ui:latest